version: '3.7'

services:
    nextcloud:
        image: ghcr.io/nextcloud/continuous-integration-shallow-server

        ports:
            - 8082:80

        environment:
            CYPRESS_baseUrl: "http://127.0.0.1:8082/index.php"
            BRANCH: "${BRANCH:-stable25}"

        volumes:
            # Using fallback to make sure this script doesn't mess
            # with the mounting if APP_NAME is not provided.
            - ../:/var/www/html/apps/${APP_NAME:-photos}
            - ./initserver.sh:/initserver.sh
