# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization

name: Block fixup and squash commits

on: pull_request

jobs:
        commit-message-check:
                name: Block fixup and squash commits

                runs-on: ubuntu-latest

                steps:
                        - name: Run check
                          uses: skjnldsv/block-fixup-merge-action@42d26e1b536ce61e5cf467d65fb76caf4aa85acf # v1
                          with:
                                  repo-token: ${{ secrets.GITHUB_TOKEN }}
